[[bsv_analyzer.assist.emitMustUse]]bsv_analyzer.assist.emitMustUse (default: `false`)::
+
--
Whether to insert #[must_use] when generating `as_` methods
for enum variants.
--
[[bsv_analyzer.assist.expressionFillDefault]]bsv_analyzer.assist.expressionFillDefault (default: `"todo"`)::
+
--
Placeholder expression to use for missing expressions in assists.
--
[[bsv_analyzer.assist.termSearch.borrowcheck]]bsv_analyzer.assist.termSearch.borrowcheck (default: `false`)::
+
--
Enable borrow checking for term search code assists. If set to false, also there will be more suggestions, but some of them may not borrow-check.
--
[[bsv_analyzer.assist.termSearch.fuel]]bsv_analyzer.assist.termSearch.fuel (default: `1800`)::
+
--
Term search fuel in "units of work" for assists (Defaults to 1800).
--
[[bsv_analyzer.cachePriming.enable]]bsv_analyzer.cachePriming.enable (default: `true`)::
+
--
Warm up caches on project load.
--
[[bsv_analyzer.cachePriming.numThreads]]bsv_analyzer.cachePriming.numThreads (default: `"physical"`)::
+
--
How many worker threads to handle priming caches. The default `0` means to pick automatically.
--
[[bsv_analyzer.cargo.allTargets]]bsv_analyzer.cargo.allTargets (default: `false`)::
+
--
Pass `--all-targets` to cargo invocation.
--
[[bsv_analyzer.cargo.autoreload]]bsv_analyzer.cargo.autoreload (default: `false`)::
+
--
Automatically refresh project info via `cargo metadata` on
`Cargo.toml` or `.cargo/config.toml` changes.
--
[[bsv_analyzer.cargo.buildScripts.enable]]bsv_analyzer.cargo.buildScripts.enable (default: `false`)::
+
--
Run build scripts (`build.rs`) for more precise code analysis.
--
[[bsv_analyzer.cargo.buildScripts.invocationStrategy]]bsv_analyzer.cargo.buildScripts.invocationStrategy (default: `"per_workspace"`)::
+
--
Specifies the invocation strategy to use when running the build scripts command.
If `per_workspace` is set, the command will be executed for each Rust workspace with the
workspace as the working directory.
If `once` is set, the command will be executed once with the opened project as the
working directory.
This config only has an effect when `#rust-analyzer.cargo.buildScripts.overrideCommand#`
is set.
--
[[bsv_analyzer.cargo.buildScripts.overrideCommand]]bsv_analyzer.cargo.buildScripts.overrideCommand (default: `null`)::
+
--
Override the command rust-analyzer uses to run build scripts and
build procedural macros. The command is required to output json
and should therefore include `--message-format=json` or a similar
option.

If there are multiple linked projects/workspaces, this command is invoked for
each of them, with the working directory being the workspace root
(i.e., the folder containing the `Cargo.toml`). This can be overwritten
by changing `#rust-analyzer.cargo.buildScripts.invocationStrategy#`.

By default, a cargo invocation will be constructed for the configured
targets and features, with the following base command line:

```bash
cargo check --quiet --workspace --message-format=json --all-targets --keep-going
```
.
--
[[bsv_analyzer.cargo.buildScripts.rebuildOnSave]]bsv_analyzer.cargo.buildScripts.rebuildOnSave (default: `false`)::
+
--
Rerun proc-macros building/build-scripts running when proc-macro
or build-script sources change and are saved.
--
[[bsv_analyzer.cargo.buildScripts.useRustcWrapper]]bsv_analyzer.cargo.buildScripts.useRustcWrapper (default: `false`)::
+
--
Use `RUSTC_WRAPPER=rust-analyzer` when running build scripts to
avoid checking unnecessary things.
--
[[bsv_analyzer.cargo.cfgs]]bsv_analyzer.cargo.cfgs::
+
--
Default:
----
{
  "debug_assertions": null,
  "miri": null
}
----
List of cfg options to enable with the given values.

--
[[bsv_analyzer.cargo.extraArgs]]bsv_analyzer.cargo.extraArgs (default: `[]`)::
+
--
Extra arguments that are passed to every cargo invocation.
--
[[bsv_analyzer.cargo.extraEnv]]bsv_analyzer.cargo.extraEnv (default: `{}`)::
+
--
Extra environment variables that will be set when running cargo, rustc
or other commands within the workspace. Useful for setting RUSTFLAGS.
--
[[bsv_analyzer.cargo.features]]bsv_analyzer.cargo.features (default: `[]`)::
+
--
List of features to activate.

Set this to `"all"` to pass `--all-features` to cargo.
--
[[bsv_analyzer.cargo.noDefaultFeatures]]bsv_analyzer.cargo.noDefaultFeatures (default: `false`)::
+
--
Whether to pass `--no-default-features` to cargo.
--
[[bsv_analyzer.cargo.sysroot]]bsv_analyzer.cargo.sysroot (default: `null`)::
+
--
Relative path to the sysroot, or "discover" to try to automatically find it via
"rustc --print sysroot".

Unsetting this disables sysroot loading.

This option does not take effect until rust-analyzer is restarted.
--
[[bsv_analyzer.cargo.sysrootSrc]]bsv_analyzer.cargo.sysrootSrc (default: `null`)::
+
--
Relative path to the sysroot library sources. If left unset, this will default to
`{cargo.sysroot}/lib/rustlib/src/rust/library`.

This option does not take effect until rust-analyzer is restarted.
--
[[bsv_analyzer.cargo.target]]bsv_analyzer.cargo.target (default: `null`)::
+
--
Compilation target override (target triple).
--
[[bsv_analyzer.cargo.targetDir]]bsv_analyzer.cargo.targetDir (default: `null`)::
+
--
Optional path to a rust-analyzer specific target directory.
This prevents rust-analyzer's `cargo check` and initial build-script and proc-macro
building from locking the `Cargo.lock` at the expense of duplicating build artifacts.

Set to `true` to use a subdirectory of the existing target directory or
set to a path relative to the workspace to use that path.
--
[[bsv_analyzer.cfg.setTest]]bsv_analyzer.cfg.setTest (default: `false`)::
+
--
Set `cfg(test)` for local crates. Defaults to true.
--
[[bsv_analyzer.checkOnSave]]bsv_analyzer.checkOnSave (default: `false`)::
+
--
Run the check command for diagnostics on save.
--
[[bsv_analyzer.check.allTargets]]bsv_analyzer.check.allTargets (default: `null`)::
+
--
Check all targets and tests (`--all-targets`). Defaults to
`#rust-analyzer.cargo.allTargets#`.
--
[[bsv_analyzer.check.command]]bsv_analyzer.check.command (default: `"check"`)::
+
--
Cargo command to use for `cargo check`.
--
[[bsv_analyzer.check.extraArgs]]bsv_analyzer.check.extraArgs (default: `[]`)::
+
--
Extra arguments for `cargo check`.
--
[[bsv_analyzer.check.extraEnv]]bsv_analyzer.check.extraEnv (default: `{}`)::
+
--
Extra environment variables that will be set when running `cargo check`.
Extends `#rust-analyzer.cargo.extraEnv#`.
--
[[bsv_analyzer.check.features]]bsv_analyzer.check.features (default: `null`)::
+
--
List of features to activate. Defaults to
`#rust-analyzer.cargo.features#`.

Set to `"all"` to pass `--all-features` to Cargo.
--
[[bsv_analyzer.check.ignore]]bsv_analyzer.check.ignore (default: `[]`)::
+
--
List of `cargo check` (or other command specified in `check.command`) diagnostics to ignore.

For example for `cargo check`: `dead_code`, `unused_imports`, `unused_variables`,...
--
[[bsv_analyzer.check.invocationStrategy]]bsv_analyzer.check.invocationStrategy (default: `"per_workspace"`)::
+
--
Specifies the invocation strategy to use when running the check command.
If `per_workspace` is set, the command will be executed for each workspace.
If `once` is set, the command will be executed once.
This config only has an effect when `#rust-analyzer.check.overrideCommand#`
is set.
--
[[bsv_analyzer.check.noDefaultFeatures]]bsv_analyzer.check.noDefaultFeatures (default: `null`)::
+
--
Whether to pass `--no-default-features` to Cargo. Defaults to
`#rust-analyzer.cargo.noDefaultFeatures#`.
--
[[bsv_analyzer.check.overrideCommand]]bsv_analyzer.check.overrideCommand (default: `null`)::
+
--
Override the command rust-analyzer uses instead of `cargo check` for
diagnostics on save. The command is required to output json and
should therefore include `--message-format=json` or a similar option
(if your client supports the `colorDiagnosticOutput` experimental
capability, you can use `--message-format=json-diagnostic-rendered-ansi`).

If you're changing this because you're using some tool wrapping
Cargo, you might also want to change
`#rust-analyzer.cargo.buildScripts.overrideCommand#`.

If there are multiple linked projects/workspaces, this command is invoked for
each of them, with the working directory being the workspace root
(i.e., the folder containing the `Cargo.toml`). This can be overwritten
by changing `#rust-analyzer.check.invocationStrategy#`.

If `$saved_file` is part of the command, rust-analyzer will pass
the absolute path of the saved file to the provided command. This is
intended to be used with non-Cargo build systems.
Note that `$saved_file` is experimental and may be removed in the future.

An example command would be:

```bash
cargo check --workspace --message-format=json --all-targets
```
.
--
[[bsv_analyzer.check.targets]]bsv_analyzer.check.targets (default: `null`)::
+
--
Check for specific targets. Defaults to `#rust-analyzer.cargo.target#` if empty.

Can be a single target, e.g. `"x86_64-unknown-linux-gnu"` or a list of targets, e.g.
`["aarch64-apple-darwin", "x86_64-apple-darwin"]`.

Aliased as `"checkOnSave.targets"`.
--
[[bsv_analyzer.check.workspace]]bsv_analyzer.check.workspace (default: `true`)::
+
--
Whether `--workspace` should be passed to `cargo check`.
If false, `-p <package>` will be passed instead.
--
[[bsv_analyzer.completion.addSemicolonToUnit]]bsv_analyzer.completion.addSemicolonToUnit (default: `false`)::
+
--
Whether to automatically add a semicolon when completing unit-returning functions.

In `match` arms it completes a comma instead.
--
[[bsv_analyzer.completion.autoimport.enable]]bsv_analyzer.completion.autoimport.enable (default: `false`)::
+
--
Toggles the additional completions that automatically add imports when completed.
Note that your client must specify the `additionalTextEdits` LSP client capability to truly have this feature enabled.
--
[[bsv_analyzer.completion.autoself.enable]]bsv_analyzer.completion.autoself.enable (default: `false`)::
+
--
Toggles the additional completions that automatically show method calls and field accesses
with `self` prefixed to them when inside a method.
--
[[bsv_analyzer.completion.callable.snippets]]bsv_analyzer.completion.callable.snippets (default: `"fill_arguments"`)::
+
--
Whether to add parenthesis and argument snippets when completing function.
--
[[bsv_analyzer.completion.fullFunctionSignatures.enable]]bsv_analyzer.completion.fullFunctionSignatures.enable (default: `false`)::
+
--
Whether to show full function/method signatures in completion docs.
--
[[bsv_analyzer.completion.hideDeprecated]]bsv_analyzer.completion.hideDeprecated (default: `false`)::
+
--
Whether to omit deprecated items from autocompletion. By default they are marked as deprecated but not hidden.
--
[[bsv_analyzer.completion.limit]]bsv_analyzer.completion.limit (default: `null`)::
+
--
Maximum number of completions to return. If `None`, the limit is infinite.
--
[[bsv_analyzer.completion.postfix.enable]]bsv_analyzer.completion.postfix.enable (default: `false`)::
+
--
Whether to show postfix snippets like `dbg`, `if`, `not`, etc.
--
[[bsv_analyzer.completion.privateEditable.enable]]bsv_analyzer.completion.privateEditable.enable (default: `false`)::
+
--
Enables completions of private items and fields that are defined in the current workspace even if they are not visible at the current position.
--
[[bsv_analyzer.completion.snippets.custom]]bsv_analyzer.completion.snippets.custom::
+
--
Default:
----
{
  "Arc::new": {
    "postfix": "arc",
    "body": "Arc::new(${receiver})",
    "requires": "std::sync::Arc",
    "description": "Put the expression into an `Arc`",
    "scope": "expr"
  },
  "Rc::new": {
    "postfix": "rc",
    "body": "Rc::new(${receiver})",
    "requires": "std::rc::Rc",
    "description": "Put the expression into an `Rc`",
    "scope": "expr"
  },
  "Box::pin": {
    "postfix": "pinbox",
    "body": "Box::pin(${receiver})",
    "requires": "std::boxed::Box",
    "description": "Put the expression into a pinned `Box`",
    "scope": "expr"
  },
  "Err": {
    "postfix": "err",
    "body": "Err(${receiver})",
    "description": "Wrap the expression in a `Result::Err`",
    "scope": "expr"
  },
  "Some": {
    "postfix": "some",
    "body": "Some(${receiver})",
    "description": "Wrap the expression in an `Option::Some`",
    "scope": "expr"
  },
  "Ok": {
    "postfix": "ok",
    "body": "Ok(${receiver})",
    "description": "Wrap the expression in a `Result::Ok`",
    "scope": "expr"
  }
}
----
Custom completion snippets.

--
[[bsv_analyzer.completion.termSearch.enable]]bsv_analyzer.completion.termSearch.enable (default: `false`)::
+
--
Whether to enable term search based snippets like `Some(foo.bar().baz())`.
--
[[bsv_analyzer.completion.termSearch.fuel]]bsv_analyzer.completion.termSearch.fuel (default: `1000`)::
+
--
Term search fuel in "units of work" for autocompletion (Defaults to 1000).
--
[[bsv_analyzer.diagnostics.disabled]]bsv_analyzer.diagnostics.disabled (default: `[]`)::
+
--
List of rust-analyzer diagnostics to disable.
--
[[bsv_analyzer.diagnostics.enable]]bsv_analyzer.diagnostics.enable (default: `true`)::
+
--
Whether to show native rust-analyzer diagnostics.
--
[[bsv_analyzer.diagnostics.experimental.enable]]bsv_analyzer.diagnostics.experimental.enable (default: `false`)::
+
--
Whether to show experimental rust-analyzer diagnostics that might
have more false positives than usual.
--
[[bsv_analyzer.diagnostics.remapPrefix]]bsv_analyzer.diagnostics.remapPrefix (default: `{}`)::
+
--
Map of prefixes to be substituted when parsing diagnostic file paths.
This should be the reverse mapping of what is passed to `rustc` as `--remap-path-prefix`.
--
[[bsv_analyzer.diagnostics.styleLints.enable]]bsv_analyzer.diagnostics.styleLints.enable (default: `false`)::
+
--
Whether to run additional style lints.
--
[[bsv_analyzer.diagnostics.warningsAsHint]]bsv_analyzer.diagnostics.warningsAsHint (default: `[]`)::
+
--
List of warnings that should be displayed with hint severity.

The warnings will be indicated by faded text or three dots in code
and will not show up in the `Problems Panel`.
--
[[bsv_analyzer.diagnostics.warningsAsInfo]]bsv_analyzer.diagnostics.warningsAsInfo (default: `[]`)::
+
--
List of warnings that should be displayed with info severity.

The warnings will be indicated by a blue squiggly underline in code
and a blue icon in the `Problems Panel`.
--
[[bsv_analyzer.files.excludeDirs]]bsv_analyzer.files.excludeDirs (default: `[]`)::
+
--
These directories will be ignored by rust-analyzer. They are
relative to the workspace root, and globs are not supported. You may
also need to add the folders to Code's `files.watcherExclude`.
--
[[bsv_analyzer.files.watcher]]bsv_analyzer.files.watcher (default: `"client"`)::
+
--
Controls file watching implementation.
--
[[bsv_analyzer.highlightRelated.breakPoints.enable]]bsv_analyzer.highlightRelated.breakPoints.enable (default: `false`)::
+
--
Enables highlighting of related references while the cursor is on `break`, `loop`, `while`, or `for` keywords.
--
[[bsv_analyzer.highlightRelated.closureCaptures.enable]]bsv_analyzer.highlightRelated.closureCaptures.enable (default: `false`)::
+
--
Enables highlighting of all captures of a closure while the cursor is on the `|` or move keyword of a closure.
--
[[bsv_analyzer.highlightRelated.exitPoints.enable]]bsv_analyzer.highlightRelated.exitPoints.enable (default: `false`)::
+
--
Enables highlighting of all exit points while the cursor is on any `return`, `?`, `fn`, or return type arrow (`->`).
--
[[bsv_analyzer.highlightRelated.references.enable]]bsv_analyzer.highlightRelated.references.enable (default: `false`)::
+
--
Enables highlighting of related references while the cursor is on any identifier.
--
[[bsv_analyzer.highlightRelated.yieldPoints.enable]]bsv_analyzer.highlightRelated.yieldPoints.enable (default: `false`)::
+
--
Enables highlighting of all break points for a loop or block context while the cursor is on any `async` or `await` keywords.
--
[[bsv_analyzer.hover.actions.debug.enable]]bsv_analyzer.hover.actions.debug.enable (default: `false`)::
+
--
Whether to show `Debug` action. Only applies when
`#rust-analyzer.hover.actions.enable#` is set.
--
[[bsv_analyzer.hover.actions.enable]]bsv_analyzer.hover.actions.enable (default: `false`)::
+
--
Whether to show HoverActions in Rust files.
--
[[bsv_analyzer.hover.actions.gotoTypeDef.enable]]bsv_analyzer.hover.actions.gotoTypeDef.enable (default: `false`)::
+
--
Whether to show `Go to Type Definition` action. Only applies when
`#rust-analyzer.hover.actions.enable#` is set.
--
[[bsv_analyzer.hover.actions.implementations.enable]]bsv_analyzer.hover.actions.implementations.enable (default: `false`)::
+
--
Whether to show `Implementations` action. Only applies when
`#rust-analyzer.hover.actions.enable#` is set.
--
[[bsv_analyzer.hover.actions.references.enable]]bsv_analyzer.hover.actions.references.enable (default: `false`)::
+
--
Whether to show `References` action. Only applies when
`#rust-analyzer.hover.actions.enable#` is set.
--
[[bsv_analyzer.hover.actions.run.enable]]bsv_analyzer.hover.actions.run.enable (default: `false`)::
+
--
Whether to show `Run` action. Only applies when
`#rust-analyzer.hover.actions.enable#` is set.
--
[[bsv_analyzer.hover.documentation.enable]]bsv_analyzer.hover.documentation.enable (default: `false`)::
+
--
Whether to show documentation on hover.
--
[[bsv_analyzer.hover.documentation.keywords.enable]]bsv_analyzer.hover.documentation.keywords.enable (default: `false`)::
+
--
Whether to show keyword hover popups. Only applies when
`#rust-analyzer.hover.documentation.enable#` is set.
--
[[bsv_analyzer.hover.links.enable]]bsv_analyzer.hover.links.enable (default: `false`)::
+
--
Use markdown syntax for links on hover.
--
[[bsv_analyzer.hover.memoryLayout.alignment]]bsv_analyzer.hover.memoryLayout.alignment (default: `"hexadecimal"`)::
+
--
How to render the align information in a memory layout hover.
--
[[bsv_analyzer.hover.memoryLayout.enable]]bsv_analyzer.hover.memoryLayout.enable (default: `false`)::
+
--
Whether to show memory layout data on hover.
--
[[bsv_analyzer.hover.memoryLayout.niches]]bsv_analyzer.hover.memoryLayout.niches (default: `false`)::
+
--
How to render the niche information in a memory layout hover.
--
[[bsv_analyzer.hover.memoryLayout.offset]]bsv_analyzer.hover.memoryLayout.offset (default: `"hexadecimal"`)::
+
--
How to render the offset information in a memory layout hover.
--
[[bsv_analyzer.hover.memoryLayout.size]]bsv_analyzer.hover.memoryLayout.size (default: `"both"`)::
+
--
How to render the size information in a memory layout hover.
--
[[bsv_analyzer.hover.show.enumVariants]]bsv_analyzer.hover.show.enumVariants (default: `5`)::
+
--
How many variants of an enum to display when hovering on. Show none if empty.
--
[[bsv_analyzer.hover.show.fields]]bsv_analyzer.hover.show.fields (default: `5`)::
+
--
How many fields of a struct, variant or union to display when hovering on. Show none if empty.
--
[[bsv_analyzer.hover.show.traitAssocItems]]bsv_analyzer.hover.show.traitAssocItems (default: `null`)::
+
--
How many associated items of a trait to display when hovering a trait.
--
[[bsv_analyzer.imports.granularity.enforce]]bsv_analyzer.imports.granularity.enforce (default: `false`)::
+
--
Whether to enforce the import granularity setting for all files. If set to false rust-analyzer will try to keep import styles consistent per file.
--
[[bsv_analyzer.imports.granularity.group]]bsv_analyzer.imports.granularity.group (default: `"crate"`)::
+
--
How imports should be grouped into use statements.
--
[[bsv_analyzer.imports.group.enable]]bsv_analyzer.imports.group.enable (default: `false`)::
+
--
Group inserted imports by the https://rust-analyzer.github.io/manual.html#auto-import[following order]. Groups are separated by newlines.
--
[[bsv_analyzer.imports.merge.glob]]bsv_analyzer.imports.merge.glob (default: `false`)::
+
--
Whether to allow import insertion to merge new imports into single path glob imports like `use std::fmt::*;`.
--
[[bsv_analyzer.imports.preferNoStd]]bsv_analyzer.imports.preferNoStd (default: `false`)::
+
--
Prefer to unconditionally use imports of the core and alloc crate, over the std crate.
--
[[bsv_analyzer.imports.preferPrelude]]bsv_analyzer.imports.preferPrelude (default: `false`)::
+
--
Whether to prefer import paths containing a `prelude` module.
--
[[bsv_analyzer.imports.prefix]]bsv_analyzer.imports.prefix (default: `"plain"`)::
+
--
The path structure for newly inserted paths to use.
--
[[bsv_analyzer.imports.prefixExternPrelude]]bsv_analyzer.imports.prefixExternPrelude (default: `false`)::
+
--
Whether to prefix external (including std, core) crate imports with `::`. e.g. "use ::std::io::Read;".
--
[[bsv_analyzer.inlayHints.bindingModeHints.enable]]bsv_analyzer.inlayHints.bindingModeHints.enable (default: `false`)::
+
--
Whether to show inlay type hints for binding modes.
--
[[bsv_analyzer.inlayHints.chainingHints.enable]]bsv_analyzer.inlayHints.chainingHints.enable (default: `false`)::
+
--
Whether to show inlay type hints for method chains.
--
[[bsv_analyzer.inlayHints.closingBraceHints.enable]]bsv_analyzer.inlayHints.closingBraceHints.enable (default: `false`)::
+
--
Whether to show inlay hints after a closing `}` to indicate what item it belongs to.
--
[[bsv_analyzer.inlayHints.closingBraceHints.minLines]]bsv_analyzer.inlayHints.closingBraceHints.minLines (default: `25`)::
+
--
Minimum number of lines required before the `}` until the hint is shown (set to 0 or 1
to always show them).
--
[[bsv_analyzer.inlayHints.closureCaptureHints.enable]]bsv_analyzer.inlayHints.closureCaptureHints.enable (default: `false`)::
+
--
Whether to show inlay hints for closure captures.
--
[[bsv_analyzer.inlayHints.closureReturnTypeHints.enable]]bsv_analyzer.inlayHints.closureReturnTypeHints.enable (default: `"never"`)::
+
--
Whether to show inlay type hints for return types of closures.
--
[[bsv_analyzer.inlayHints.closureStyle]]bsv_analyzer.inlayHints.closureStyle (default: `"impl_fn"`)::
+
--
Closure notation in type and chaining inlay hints.
--
[[bsv_analyzer.inlayHints.discriminantHints.enable]]bsv_analyzer.inlayHints.discriminantHints.enable (default: `"never"`)::
+
--
Whether to show enum variant discriminant hints.
--
[[bsv_analyzer.inlayHints.expressionAdjustmentHints.enable]]bsv_analyzer.inlayHints.expressionAdjustmentHints.enable (default: `"never"`)::
+
--
Whether to show inlay hints for type adjustments.
--
[[bsv_analyzer.inlayHints.expressionAdjustmentHints.hideOutsideUnsafe]]bsv_analyzer.inlayHints.expressionAdjustmentHints.hideOutsideUnsafe (default: `false`)::
+
--
Whether to hide inlay hints for type adjustments outside of `unsafe` blocks.
--
[[bsv_analyzer.inlayHints.expressionAdjustmentHints.mode]]bsv_analyzer.inlayHints.expressionAdjustmentHints.mode (default: `"prefix"`)::
+
--
Whether to show inlay hints as postfix ops (`.*` instead of `*`, etc).
--
[[bsv_analyzer.inlayHints.genericParameterHints.const.enable]]bsv_analyzer.inlayHints.genericParameterHints.const.enable (default: `false`)::
+
--
Whether to show const generic parameter name inlay hints.
--
[[bsv_analyzer.inlayHints.genericParameterHints.lifetime.enable]]bsv_analyzer.inlayHints.genericParameterHints.lifetime.enable (default: `false`)::
+
--
Whether to show generic lifetime parameter name inlay hints.
--
[[bsv_analyzer.inlayHints.genericParameterHints.type.enable]]bsv_analyzer.inlayHints.genericParameterHints.type.enable (default: `false`)::
+
--
Whether to show generic type parameter name inlay hints.
--
[[bsv_analyzer.inlayHints.implicitDrops.enable]]bsv_analyzer.inlayHints.implicitDrops.enable (default: `false`)::
+
--
Whether to show implicit drop hints.
--
[[bsv_analyzer.inlayHints.lifetimeElisionHints.enable]]bsv_analyzer.inlayHints.lifetimeElisionHints.enable (default: `"never"`)::
+
--
Whether to show inlay type hints for elided lifetimes in function signatures.
--
[[bsv_analyzer.inlayHints.lifetimeElisionHints.useParameterNames]]bsv_analyzer.inlayHints.lifetimeElisionHints.useParameterNames (default: `false`)::
+
--
Whether to prefer using parameter names as the name for elided lifetime hints if possible.
--
[[bsv_analyzer.inlayHints.maxLength]]bsv_analyzer.inlayHints.maxLength (default: `25`)::
+
--
Maximum length for inlay hints. Set to null to have an unlimited length.
--
[[bsv_analyzer.inlayHints.parameterHints.enable]]bsv_analyzer.inlayHints.parameterHints.enable (default: `false`)::
+
--
Whether to show function parameter name inlay hints at the call
site.
--
[[bsv_analyzer.inlayHints.rangeExclusiveHints.enable]]bsv_analyzer.inlayHints.rangeExclusiveHints.enable (default: `false`)::
+
--
Whether to show exclusive range inlay hints.
--
[[bsv_analyzer.inlayHints.reborrowHints.enable]]bsv_analyzer.inlayHints.reborrowHints.enable (default: `"never"`)::
+
--
Whether to show inlay hints for compiler inserted reborrows.
This setting is deprecated in favor of #rust-analyzer.inlayHints.expressionAdjustmentHints.enable#.
--
[[bsv_analyzer.inlayHints.renderColons]]bsv_analyzer.inlayHints.renderColons (default: `false`)::
+
--
Whether to render leading colons for type hints, and trailing colons for parameter hints.
--
[[bsv_analyzer.inlayHints.typeHints.enable]]bsv_analyzer.inlayHints.typeHints.enable (default: `false`)::
+
--
Whether to show inlay type hints for variables.
--
[[bsv_analyzer.inlayHints.typeHints.hideClosureInitialization]]bsv_analyzer.inlayHints.typeHints.hideClosureInitialization (default: `false`)::
+
--
Whether to hide inlay type hints for `let` statements that initialize to a closure.
Only applies to closures with blocks, same as `#rust-analyzer.inlayHints.closureReturnTypeHints.enable#`.
--
[[bsv_analyzer.inlayHints.typeHints.hideNamedConstructor]]bsv_analyzer.inlayHints.typeHints.hideNamedConstructor (default: `false`)::
+
--
Whether to hide inlay type hints for constructors.
--
[[bsv_analyzer.interpret.tests]]bsv_analyzer.interpret.tests (default: `false`)::
+
--
Enables the experimental support for interpreting tests.
--
[[bsv_analyzer.joinLines.joinAssignments]]bsv_analyzer.joinLines.joinAssignments (default: `false`)::
+
--
Join lines merges consecutive declaration and initialization of an assignment.
--
[[bsv_analyzer.joinLines.joinElseIf]]bsv_analyzer.joinLines.joinElseIf (default: `false`)::
+
--
Join lines inserts else between consecutive ifs.
--
[[bsv_analyzer.joinLines.removeTrailingComma]]bsv_analyzer.joinLines.removeTrailingComma (default: `false`)::
+
--
Join lines removes trailing commas.
--
[[bsv_analyzer.joinLines.unwrapTrivialBlock]]bsv_analyzer.joinLines.unwrapTrivialBlock (default: `false`)::
+
--
Join lines unwraps trivial blocks.
--
[[bsv_analyzer.lens.debug.enable]]bsv_analyzer.lens.debug.enable (default: `false`)::
+
--
Whether to show `Debug` lens. Only applies when
`#rust-analyzer.lens.enable#` is set.
--
[[bsv_analyzer.lens.enable]]bsv_analyzer.lens.enable (default: `false`)::
+
--
Whether to show CodeLens in Rust files.
--
[[bsv_analyzer.lens.implementations.enable]]bsv_analyzer.lens.implementations.enable (default: `false`)::
+
--
Whether to show `Implementations` lens. Only applies when
`#rust-analyzer.lens.enable#` is set.
--
[[bsv_analyzer.lens.location]]bsv_analyzer.lens.location (default: `"above_name"`)::
+
--
Where to render annotations.
--
[[bsv_analyzer.lens.references.adt.enable]]bsv_analyzer.lens.references.adt.enable (default: `false`)::
+
--
Whether to show `References` lens for Struct, Enum, and Union.
Only applies when `#rust-analyzer.lens.enable#` is set.
--
[[bsv_analyzer.lens.references.enumVariant.enable]]bsv_analyzer.lens.references.enumVariant.enable (default: `false`)::
+
--
Whether to show `References` lens for Enum Variants.
Only applies when `#rust-analyzer.lens.enable#` is set.
--
[[bsv_analyzer.lens.references.method.enable]]bsv_analyzer.lens.references.method.enable (default: `false`)::
+
--
Whether to show `Method References` lens. Only applies when
`#rust-analyzer.lens.enable#` is set.
--
[[bsv_analyzer.lens.references.trait.enable]]bsv_analyzer.lens.references.trait.enable (default: `false`)::
+
--
Whether to show `References` lens for Trait.
Only applies when `#rust-analyzer.lens.enable#` is set.
--
[[bsv_analyzer.lens.run.enable]]bsv_analyzer.lens.run.enable (default: `false`)::
+
--
Whether to show `Run` lens. Only applies when
`#rust-analyzer.lens.enable#` is set.
--
[[bsv_analyzer.linkedProjects]]bsv_analyzer.linkedProjects (default: `[]`)::
+
--
Disable project auto-discovery in favor of explicitly specified set
of projects.

Elements must be paths pointing to `Cargo.toml`,
`rust-project.json`, `.rs` files (which will be treated as standalone files) or JSON
objects in `rust-project.json` format.
--
[[bsv_analyzer.lru.capacity]]bsv_analyzer.lru.capacity (default: `null`)::
+
--
Number of syntax trees rust-analyzer keeps in memory. Defaults to 128.
--
[[bsv_analyzer.lru.query.capacities]]bsv_analyzer.lru.query.capacities (default: `{}`)::
+
--
Sets the LRU capacity of the specified queries.
--
[[bsv_analyzer.notifications.cargoTomlNotFound]]bsv_analyzer.notifications.cargoTomlNotFound (default: `false`)::
+
--
Whether to show `can't find Cargo.toml` error message.
--
[[bsv_analyzer.numThreads]]bsv_analyzer.numThreads (default: `null`)::
+
--
How many worker threads in the main loop. The default `null` means to pick automatically.
--
[[bsv_analyzer.procMacro.attributes.enable]]bsv_analyzer.procMacro.attributes.enable (default: `false`)::
+
--
Expand attribute macros. Requires `#rust-analyzer.procMacro.enable#` to be set.
--
[[bsv_analyzer.procMacro.enable]]bsv_analyzer.procMacro.enable (default: `false`)::
+
--
Enable support for procedural macros, implies `#rust-analyzer.cargo.buildScripts.enable#`.
--
[[bsv_analyzer.procMacro.ignored]]bsv_analyzer.procMacro.ignored (default: `{}`)::
+
--
These proc-macros will be ignored when trying to expand them.

This config takes a map of crate names with the exported proc-macro names to ignore as values.
--
[[bsv_analyzer.procMacro.server]]bsv_analyzer.procMacro.server (default: `null`)::
+
--
Internal config, path to proc-macro server executable.
--
[[bsv_analyzer.references.excludeImports]]bsv_analyzer.references.excludeImports (default: `false`)::
+
--
Exclude imports from find-all-references.
--
[[bsv_analyzer.references.excludeTests]]bsv_analyzer.references.excludeTests (default: `false`)::
+
--
Exclude tests from find-all-references.
--
[[bsv_analyzer.runnables.command]]bsv_analyzer.runnables.command (default: `null`)::
+
--
Command to be executed instead of 'cargo' for runnables.
--
[[bsv_analyzer.runnables.extraArgs]]bsv_analyzer.runnables.extraArgs (default: `[]`)::
+
--
Additional arguments to be passed to cargo for runnables such as
tests or binaries. For example, it may be `--release`.
--
[[bsv_analyzer.runnables.extraTestBinaryArgs]]bsv_analyzer.runnables.extraTestBinaryArgs::
+
--
Default:
----
[
  "--show-output"
]
----
Additional arguments to be passed through Cargo to launched tests, benchmarks, or
doc-tests.

Unless the launched target uses a
[custom test harness](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#the-harness-field),
they will end up being interpreted as options to
[`rustc`’s built-in test harness (“libtest”)](https://doc.rust-lang.org/rustc/tests/index.html#cli-arguments).

--
[[bsv_analyzer.rustc.source]]bsv_analyzer.rustc.source (default: `null`)::
+
--
Path to the Cargo.toml of the rust compiler workspace, for usage in rustc_private
projects, or "discover" to try to automatically find it if the `rustc-dev` component
is installed.

Any project which uses rust-analyzer with the rustcPrivate
crates must set `[package.metadata.rust-analyzer] rustc_private=true` to use it.

This option does not take effect until rust-analyzer is restarted.
--
[[bsv_analyzer.rustfmt.extraArgs]]bsv_analyzer.rustfmt.extraArgs (default: `[]`)::
+
--
Additional arguments to `rustfmt`.
--
[[bsv_analyzer.rustfmt.overrideCommand]]bsv_analyzer.rustfmt.overrideCommand (default: `null`)::
+
--
Advanced option, fully override the command rust-analyzer uses for
formatting. This should be the equivalent of `rustfmt` here, and
not that of `cargo fmt`. The file contents will be passed on the
standard input and the formatted result will be read from the
standard output.
--
[[bsv_analyzer.rustfmt.rangeFormatting.enable]]bsv_analyzer.rustfmt.rangeFormatting.enable (default: `false`)::
+
--
Enables the use of rustfmt's unstable range formatting command for the
`textDocument/rangeFormatting` request. The rustfmt option is unstable and only
available on a nightly build.
--
[[bsv_analyzer.semanticHighlighting.doc.comment.inject.enable]]bsv_analyzer.semanticHighlighting.doc.comment.inject.enable (default: `false`)::
+
--
Inject additional highlighting into doc comments.

When enabled, rust-analyzer will highlight rust source in doc comments as well as intra
doc links.
--
[[bsv_analyzer.semanticHighlighting.nonStandardTokens]]bsv_analyzer.semanticHighlighting.nonStandardTokens (default: `false`)::
+
--
Whether the server is allowed to emit non-standard tokens and modifiers.
--
[[bsv_analyzer.semanticHighlighting.operator.enable]]bsv_analyzer.semanticHighlighting.operator.enable (default: `false`)::
+
--
Use semantic tokens for operators.

When disabled, rust-analyzer will emit semantic tokens only for operator tokens when
they are tagged with modifiers.
--
[[bsv_analyzer.semanticHighlighting.operator.specialization.enable]]bsv_analyzer.semanticHighlighting.operator.specialization.enable (default: `false`)::
+
--
Use specialized semantic tokens for operators.

When enabled, rust-analyzer will emit special token types for operator tokens instead
of the generic `operator` token type.
--
[[bsv_analyzer.semanticHighlighting.punctuation.enable]]bsv_analyzer.semanticHighlighting.punctuation.enable (default: `false`)::
+
--
Use semantic tokens for punctuation.

When disabled, rust-analyzer will emit semantic tokens only for punctuation tokens when
they are tagged with modifiers or have a special role.
--
[[bsv_analyzer.semanticHighlighting.punctuation.separate.macro.bang]]bsv_analyzer.semanticHighlighting.punctuation.separate.macro.bang (default: `false`)::
+
--
When enabled, rust-analyzer will emit a punctuation semantic token for the `!` of macro
calls.
--
[[bsv_analyzer.semanticHighlighting.punctuation.specialization.enable]]bsv_analyzer.semanticHighlighting.punctuation.specialization.enable (default: `false`)::
+
--
Use specialized semantic tokens for punctuation.

When enabled, rust-analyzer will emit special token types for punctuation tokens instead
of the generic `punctuation` token type.
--
[[bsv_analyzer.semanticHighlighting.strings.enable]]bsv_analyzer.semanticHighlighting.strings.enable (default: `false`)::
+
--
Use semantic tokens for strings.

In some editors (e.g. vscode) semantic tokens override other highlighting grammars.
By disabling semantic tokens for strings, other grammars can be used to highlight
their contents.
--
[[bsv_analyzer.signatureInfo.detail]]bsv_analyzer.signatureInfo.detail (default: `"full"`)::
+
--
Show full signature of the callable. Only shows parameters if disabled.
--
[[bsv_analyzer.signatureInfo.documentation.enable]]bsv_analyzer.signatureInfo.documentation.enable (default: `false`)::
+
--
Show documentation.
--
[[bsv_analyzer.typing.autoClosingAngleBrackets.enable]]bsv_analyzer.typing.autoClosingAngleBrackets.enable (default: `false`)::
+
--
Whether to insert closing angle brackets when typing an opening angle bracket of a generic argument list.
--
[[bsv_analyzer.workspace.discoverConfig]]bsv_analyzer.workspace.discoverConfig (default: `null`)::
+
--
Enables automatic discovery of projects using [`DiscoverWorkspaceConfig::command`].

[`DiscoverWorkspaceConfig`] also requires setting `progress_label` and `files_to_watch`.
`progress_label` is used for the title in progress indicators, whereas `files_to_watch`
is used to determine which build system-specific files should be watched in order to
reload rust-analyzer.

Below is an example of a valid configuration:
```json
"rust-analyzer.workspace.discoverConfig": {
    "command": [
        "rust-project",
        "develop-json"
    ],
    "progressLabel": "rust-analyzer",
    "filesToWatch": [
        "BUCK"
    ]
}
```

## On `DiscoverWorkspaceConfig::command`

**Warning**: This format is provisional and subject to change.

[`DiscoverWorkspaceConfig::command`] *must* return a JSON object
corresponding to `DiscoverProjectData::Finished`:

```norun
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(tag = "kind")]
#[serde(rename_all = "snake_case")]
enum DiscoverProjectData {
    Finished { buildfile: Utf8PathBuf, project: ProjectJsonData },
    Error { error: String, source: Option<String> },
    Progress { message: String },
}
```

As JSON, `DiscoverProjectData::Finished` is:

```json
{
    // the internally-tagged representation of the enum.
    "kind": "finished",
    // the file used by a non-Cargo build system to define
    // a package or target.
    "buildfile": "rust-analyzer/BUILD",
    // the contents of a rust-project.json, elided for brevity
    "project": {
        "sysroot": "foo",
        "crates": []
    }
}
```

It is encouraged, but not required, to use the other variants on
`DiscoverProjectData` to provide a more polished end-user experience.

`DiscoverWorkspaceConfig::command` may *optionally* include an `{arg}`,
which will be substituted with the JSON-serialized form of the following
enum:

```norun
#[derive(PartialEq, Clone, Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub enum DiscoverArgument {
   Path(AbsPathBuf),
   Buildfile(AbsPathBuf),
}
```

The JSON representation of `DiscoverArgument::Path` is:

```json
{
    "path": "src/main.rs"
}
```

Similarly, the JSON representation of `DiscoverArgument::Buildfile` is:

```
{
    "buildfile": "BUILD"
}
```

`DiscoverArgument::Path` is used to find and generate a `rust-project.json`,
and therefore, a workspace, whereas `DiscoverArgument::buildfile` is used to
to update an existing workspace. As a reference for implementors,
buck2's `rust-project` will likely be useful:
https://github.com/facebook/buck2/tree/main/integrations/rust-project.
--
[[bsv_analyzer.workspace.symbol.search.kind]]bsv_analyzer.workspace.symbol.search.kind (default: `"only_types"`)::
+
--
Workspace symbol search kind.
--
[[bsv_analyzer.workspace.symbol.search.limit]]bsv_analyzer.workspace.symbol.search.limit (default: `128`)::
+
--
Limits the number of items returned from a workspace symbol search (Defaults to 128).
Some clients like vs-code issue new searches on result filtering and don't require all results to be returned in the initial search.
Other clients requires all results upfront and might require a higher limit.
--
[[bsv_analyzer.workspace.symbol.search.scope]]bsv_analyzer.workspace.symbol.search.scope (default: `"workspace"`)::
+
--
Workspace symbol search scope.
--
